name: Node.js Application with GitHub Secrets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version

      # Step 3: Initialize 
      - name: Initialize the npm 
        run: npm init -y


      # Step 3: Install dependencies
      # - name: Install dependencies
      #   run: npm install

      # Step 4: Run the application
      # - name: Start application with secret
      #   env:
      #     API_KEY: ${{ secrets.API_KEY }}
      #   run: |
      #     node index.js
